---

- name: Ensure apt cache is up to date
  become: true
  become_user: root
  apt:
    update_cache: yes
    cache_valid_time: "{{ 48 * 60 * 60 }}"  # consider the cache to be valid within 48 hours


- name: Install the packages postgresql-client & python3-psycopg2
  become: true
  become_user: root
  apt:
    pkg:
      - postgresql-client
      - python3-psycopg2
    state: present



- name: Create users to access the DB
  postgresql_user:
    login_host: "localhost"
    login_user: "{{ db_user }}"
    login_password: "{{ db_password }}"
    db: "{{ item.db }}"
    port: "{{ expose_postgresql_port | default(omit) }}"
    name: "{{ item.name }}"
    password: "{{ item.password }}"
  loop: "{{ expose_postgresql_users }}"
  no_log: false
  when: expose_postgresql_users is defined

- name: GRANT privs for DB user
  postgresql_privs:
    login_host: "localhost"
    login_user: "{{ db_user }}"
    login_password: "{{ db_password }}"
    database: "{{ item.db }}"
    port: "{{ expose_postgresql_port | default(omit) }}"
    roles: "{{ item.name }}"
    objs: "{{ item.objs }}"
    privs: "{{ item.privs }}"
  loop: "{{ expose_postgresql_users }}"
  no_log: false
  when: expose_postgresql_users is defined

