---
system_administrators:
  - name: kon
    ssh_key: "{{ inventory_dir }}/../pub_keys/kon.pub"
    state: present
  - name: jordi
    ssh_key: "{{ inventory_dir }}/../pub_keys/jordi.pub"
    state: present
  - name: silvia
    ssh_key: "{{ inventory_dir }}/../pub_keys/silvia.pub"
    state: present
  - name: amoved
    ssh_key: "{{ inventory_dir }}/../pub_keys/amoved.pub"
    state: present

domains:
  - test.ensenyaelcor.org
  - test.ensenaelcorazon.org
  - test.bihotzaerakutsi.org
  - test.ensinaocorazon.org

developers: []

# Let's Encrypt conf
certificate_authority_email: sysadmin@coopdevs.org

# Set 'development_environment' to "true" to skip SSL and nginx tasks
development_environment: False

# Disable backups
backups_role_enabled: False

postgresql_python_library: python3-psycopg2

security_enabled: False
firewall_enabled: True
